// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBket9dXAiFfhdpl2NQSB77zbv6HuAWG7M',
    appId: '1:991304883085:web:6c47cacfebe5c89d6b3bc4',
    messagingSenderId: '991304883085',
    projectId: 'notifications-ce6e8',
    authDomain: 'notifications-ce6e8.firebaseapp.com',
    storageBucket: 'notifications-ce6e8.firebasestorage.app',
    measurementId: 'G-W5HQZP2R8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKr6aTnm1YtnoA-KWBlLhDPwATNDLIYM',
    appId: '1:991304883085:android:674eeae8ee0ca92d6b3bc4',
    messagingSenderId: '991304883085',
    projectId: 'notifications-ce6e8',
    storageBucket: 'notifications-ce6e8.firebasestorage.app',
  );
}
